webpack, babel, eslint, prettier 설정
woowa-techcamp-2021/cashbook-20 pull request #1
Opened 2021-07-26 06:51 UTC by jiyong1

2021-07-26 06:52 UTC, juyoungpark718 approved these changes
LGTM  ! 바꿀게 없습니다 !

2021-07-26 06:53 UTC, juyoungpark718 requested changes
리뷰 테스트 !

2021-07-26 06:53 UTC, juyoungpark718 approved these changes
너무 좋습니다 ! 👍

2021-07-26 06:53 UTC, merged

2021-07-30 05:11 UTC, Kyun2da commented
> LGTM ! 바꿀게 없습니다 !

Looks Good To Me 배워갑니당~