nav바 마크업 및 기능, store setstate 변경, router 비동기 middleware 기능
woowa-techcamp-2021/cashbook-20 pull request #20
Opened 2021-07-28 11:12 UTC by jiyong1

- 아까 말씀드렸던 store setState 버그 수정
- router 미들웨어 비동기로 처리 가능
- nav 바 마크업과 기능 완료
  - 아직 초안이라 버그가 있을 수 있으니 사용 중 버그 생기면 이슈 등록해주세요 ~

2021-07-28 12:27 UTC, juyoungpark718 requested changes
논의가 필요해 보이는 부분 코멘트 했습니다 !! 확인해주시면 감사하겠습니다!

2021-07-28 12:27 UTC, juyoungpark718 commented on client/src/lib/router.ts
> +      else if (funcType === 'AsyncFunction') {
else if말고 if로 적어도 되겠군요.. ㅎㅎ 취향차이인듯 합니다.

2021-07-28 12:27 UTC, juyoungpark718 commented on client/webpack.config.js
> +          ? JSON.stringify('https://github.com/login/oauth/authorize?client_id=e009a04ee3ec22e75d33')
아까 오류가 났던 부분을 이렇게 해결하셨군요.. 왜 이렇게 해야하는지 궁금하네요 ..

2021-07-28 12:27 UTC, juyoungpark718 commented on client/src/utils.ts
> +};
qsa도 qs와 비슷한 형식으로 고치는 것도 좋겠네요 !

2021-07-28 12:27 UTC, juyoungpark718 commented on client/src/lib/store.ts
> +      });
제가 찾지 못한 버그 찾아주셔서 감사합니다 :) 👍

2021-07-28 12:27 UTC, juyoungpark718 commented on client/src/scss/theme.scss
> +}
오 이런 mixin 아주 편리하겠네요!

2021-07-28 12:27 UTC, juyoungpark718 commented on client/src/component/Nav.ts
> +    console.log(routeActive);
앗 콘솔로그 ! 저희 안쓰는 콘솔로그는 지우는게 좋을까요??

2021-07-28 12:27 UTC, juyoungpark718 commented on client/src/component/Nav.ts
>        router.to('/calendar');
() => router.to(path) 와 같은 함수들이 중복되는데, 나중에 리펙토링할 때 함수로 분리해서 하는 것도 나쁘지 않겠네요

2021-07-28 12:27 UTC, juyoungpark718 commented on client/src/component/Nav.ts
> +  shouldComponentUpdate(prevState: any, nextState: any) {
prevState, nextState 타입은 정해줄 수 없을까요. 흠... store/index.ts에 있는 IRootState를 상속받는 state를 타입으로 가져도 좋을 것 같아요!

2021-07-28 12:27 UTC, juyoungpark718 commented on client/src/scss/nav.scss
> +  > h1 {
`>` 을 다 써주셨는데, scss에서

```scss
.nav-wrapper{
   .nav-center{}
}

.nav-wrapper{
   > .nav-center{}
}
```

두 개가 뭐가 다른지 제가 잘 몰라서 혹시 어떤게 다른걸까요 ?? 🤔

2021-07-28 12:30 UTC, jiyong1 commented on client/src/lib/router.ts
> +      else if (funcType === 'AsyncFunction') {
if 문을 그대로 사용하게 되면..
일반 함수이지만, 미들웨어서 true를 리턴했을 때 또 다시 밑에 if 문을 통해서 비동기 함수인지에 대한 검증이 이루어지기 때문에 else if를 사용했습니다 !

2021-07-28 12:31 UTC, jiyong1 commented on client/webpack.config.js
> +          ? JSON.stringify('https://github.com/login/oauth/authorize?client_id=e009a04ee3ec22e75d33')
오류나는 쪽을 확인해보니 전달이 string형태로 안되더라구요..
그래서 구글링 해보니 다들 한번 더 스트링으로 변환해주는 걸 확인했습니다 !

2021-07-28 12:31 UTC, jiyong1 commented on client/src/utils.ts
> +};
아 동의합니다 이부분 수정해서 다시 커밋 보내겠습니다 !

2021-07-28 12:31 UTC, jiyong1 commented on client/src/lib/store.ts
> +      });
ㅋㅋㅋ 아닙니다 ~

2021-07-28 12:32 UTC, jiyong1 commented on client/src/scss/theme.scss
> +}
사실 더 추가하면 할 수 있는데.. 일단 nav바 스타일링에 집중하다보니 추가 못했습니다..
앞으로 mixin 추가하시면 말씀해주세요 ㅎㅎ 용이하게 쓰겠습니다 ㅎㅎ

2021-07-28 12:32 UTC, jiyong1 commented on client/src/component/Nav.ts
> +    console.log(routeActive);
앗..ㅋㅋㅋㅋㅋ이부분도 지우고 커밋 남기겠습니다 ㅎㅎ

2021-07-28 12:33 UTC, jiyong1 commented on client/src/component/Nav.ts
>        router.to('/calendar');
좋습니다 ㅎㅎ 리팩토링 때 진행하시죠~

2021-07-28 12:35 UTC, jiyong1 commented on client/src/scss/nav.scss
> +  > h1 {
바로 아래 자식이냐 혹은 손자의 손자까지 쭉 포함한 자손이느냐 입니다ㅎㅎ
아무래도 저희가 컴포넌트 작업을 따로 하다 보면 클래스 내용이 겹칠 수 있는 가능성이 있기 때문에 왠만하면 타이트하게 자식이라고 특정 짓는게 좋아보여서 저렇게 작성했습니다
```
'>' 자식
'' 자손
```

2021-07-28 12:52 UTC, juyoungpark718 commented on client/src/scss/nav.scss
> +  > h1 {
아 자식이랑 자손이랑 완전히 다르군요! 배워갑니다 !

2021-07-28 12:53 UTC, jiyong1 commented on client/src/component/Nav.ts
> +  shouldComponentUpdate(prevState: any, nextState: any) {
음 모든 컴포넌트가 state를 가질 수 있는데..
그래서 state를 특정짓기 어려울 것 같습니다.

2021-07-28 12:54 UTC, juyoungpark718 approved these changes
LGTM !! 고생하셨습니다 !!

2021-07-28 12:54 UTC, merged

2021-07-30 05:11 UTC, TsooranKim commented
LOL!